region:
  country_code: "CL"
  currency_code: "CLP"
  locale: "es-CL"
  timezone_iana: "America/Santiago"

payment:
  supported_methods:
    - id: "webpay"
      type: "transfer"
      name: "Webpay"
      min_amount: 350.0
      max_amount: 5000000.0
      processing_time: "instant"
      
    - id: "servipag"
      type: "cash"
      name: "Servipag"
      min_amount: 1000.0
      max_amount: 500000.0
      processing_time: "24h"
      
    - id: "credit_card"
      type: "card"
      name: "Tarjeta de Credito"
      min_amount: 350.0
      max_amount: 5000000.0
      processing_time: "instant"
      
    - id: "debit_card"
      type: "card"
      name: "Tarjeta de Debito"
      min_amount: 350.0
      max_amount: 2000000.0
      processing_time: "instant"
      
    - id: "account_money"
      type: "wallet"
      name: "Dinero en Cuenta"
      min_amount: 1.0
      max_amount: 10000000.0
      processing_time: "instant"

  min_amount: 350.0
  max_amount: 50000000.0
  max_amount_without_kyc: 500000.0
  
  supports_refunds: true
  supports_partial_refunds: true
  supports_installments: true
  max_installments: 12
  
  supported_currencies:
    - "CLP"
  
  requires_kyc: true
  requires_tax_id: true

shipment:
  supported_carriers:
    - id: "chilexpress"
      name: "Chilexpress"
      service_types: ["standard", "express"]
      coverage_zones: ["national"]
      
    - id: "starken"
      name: "Starken"
      service_types: ["standard"]
      coverage_zones: ["national"]
      
    - id: "bluexpress"
      name: "Blue Express"
      service_types: ["express"]
      coverage_zones: ["metropolitan"]

  supports_tracking: true
  supports_label_print: true
  supports_scheduled_pickup: true
  supports_cancellation: true
  
  max_weight_kg: 30.0
  max_dimensions_cm:
    length: 100.0
    width: 80.0
    height: 80.0

qr:
  supported: true
  supports_dynamic_qr: true
  supports_static_qr: true
  max_expiration_minutes: 30
  min_amount: 350.0
  max_amount: 500000.0
  requires_pos_registration: true

rate_limits:
  requests_per_second: 15
  requests_per_minute: 450
  concurrent_connections: 8
